### ISSUE TITLE
Vertex swapping

### ISSUE THREAD

**Issue by andrewtheone** [SeanNikkel/VoxelEngine#1]
Hi!

I was looking at your code, and I just cant figure out why you're swapping the vertexes here: https://github.com/SeanNikkel/Voxel/blob/master/src/Mesh.cpp#L101
Actually I don't understand the condition itself, can you explain it to me?

**Comment by SeanNikkel** [comment]
The ambient occlusion is based off of this article:

https://0fps.net/2013/07/03/ambient-occlusion-for-minecraft-like-worlds/#attachment_1325

The interpolation between the ambient occlusion values of the vertices looks different depending on how the quad is oriented, so sometimes it needs to be flipped to look consistent. The if statement tests which diagonal corners have the darker values, and flips the quad accordingly.
