### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by AMoser96** [SeanNikkel/VoxelEngine#2]
Hi,
I'm writing a master's thesis about voxel rendering and would like to use your voxel engine as a basic implementation.
However, your repository doesn't have a license yet.
Therefore I would like to ask if it would be possible for you to add one? (e.g. MIT-License: https://choosealicense.com/licenses/mit/#suggest-this-license)

Thanks in advance!

**Comment by SeanNikkel** [comment]
Added it! Good luck with your thesis, and let me know if you need anything else!
